### ISSUE TITLE
The cutting block: These features will be removed from itertools eventually

### ISSUE THREAD

**Issue by bluss** [rust-itertools/itertools#223]
- [x] `.foreach()` -- when `Iterator::for_each` stabilizes and it's old enough so that the deprecation is not annoying. Introduced in Rust 1.21. **Deprecated in 0.8**
- [x] `.step()` #133 -- when `Iterator::step_by` stabilizes rust-lang/rust/issues/27741 Rust 1.28 **Deprecated in 0.8**
- [x] `.fold_while()` when `Iterator::try_fold` is stable Rust 1.27 **Deprecated in 0.8**
- [x] `repeat_call` when `repeat_with` is stable rust-lang/rust/pull/48156 Rust 1.28  **Deprecated in 0.8**
- [x] `.flatten()` when `Iterator::flatten` is stable #262  Rust 1.29 **Removed in 0.8**
- [x] `unfold()` when `std::iter::unfold` is stable rust-lang/rust/issues/55977

**Comment by flxo** [comment]
Looks like `.flatten()` hit [stable](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.flatten) with 1.29.

**Comment by DevinR528** [comment]
Seems like `unfold` was merged in as `from_fn`, issue may now be close-able?
